---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)

library(terra)
library(sf)
library(whitebox)
library(httr)
library(arcpullr) #would be cool if it worked but right now it does not seem to work right 
library(rgee)

library(ForestTools)
library(lidR)


```

# Downloading DEM Tiles
```{r}
image_service_url <- "https://gis.dogami.oregon.gov/arcgis/rest/services/lidar/CANOPY_HEIGHT_MODEL_MOSAIC/ImageServer"


aoi <-st_read("OregonLidarData.gpkg", layer = "AOI")
aoi<- sf::st_transform(aoi, "EPSG:4326")
bbox <-st_bbox(aoi)

# Queary the image service
query_url <- paste0(
  image_service_url,
  "/exportImage?bbox=",
  paste(bbox, collapse = ","),
  "&bboxSR=4326&size=1000,1000&imageSR=4326&format=tiff&f=image"
)

response <- httr::GET(query_url)

if (response$status_code == 200) {
  # Write the content to a file
  writeBin(httr::content(response, "raw"), "output.tiff")
} else {
  stop("Failed to retrieve raster data.")
}

raster_data <- rast("output.tiff")
plot(raster_data)

```


# Google Earth Engine - WORK IN PROGRSS
to compare the differences between the Oregon LiDAR and Meta 1m Tree data

```{r}
# If required run ee_Authenticate()

ee_Authenticate(auth_mode='notebook')
ee_Initialize(project = "ee-frmstf")
```

```{r}
canopy_ht <- ee$ImageCollection("projects/meta-forest-monitoring-okw37/assets/CanopyHeight")
gee_aoi <- ee$Geometry$Rectangle(bbox)

canopy_ht_image <- canopy_ht_collection$filterBounds(region)$first()

local_path <- "canopy_height.tif"

ee_as_raster(
  image = canopy_ht_image,
  region = region,
  scale = 30,  # Adjust the scale (resolution) as needed
  dsn = local_path
)
```




